faq/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq_list, name='faq_list'),
    path('new/', views.new_faq, name='new_faq'),
    path('json/', views.faq_json, name='json'),
]

landing/urls.py
from django.urls import path, include
from landing.views import index
from landing.views import add_product
from landing.views import see_desc
from django.conf import settings
from django.conf.urls.static import static
from landing.views import logout_account
from landing.views import login_page
from landing.views import signup_page
from landing.views import newest_product

app_name = "landing"

urlpatterns = [
    path("", index, name='index'),
    path("addproduct/", add_product, name='add_my_product'),
    path("desc", index, name="description2"),
    path("desc/<int:id>/", see_desc, name="description"),
    path("login/", login_page, name="login_page"),
    path("signup/", signup_page, name="signup_page"),
    path("logout/", logout_account, name="logout_account"),
    path("ajax_call_products", newest_product, name="ajax_call"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yourpets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("landing.urls")),
    path("", include("barang.urls")),
    path("", include("pembayaran.urls")),
    path("", include("testimoni.urls")),
    path("faqs/", include("faq.urls"))
]

landing/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Product(models.Model):
    name = models.TextField()
    imgProduct = models.ImageField(upload_to = "images/", default="static/default/default.jpg")
    price = models.IntegerField()
    category = models.TextField()
    description = models.TextField()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=150)

    def __str__(self):
        return self.user.username
        
@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

landing/forms.py
from django import forms
from .models import Product
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class MakeProduct(forms.ModelForm):
    
    name = forms.CharField(
        label = "name", widget = forms.TextInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default"
        }),

    )

    imgProduct = forms.ImageField(
        label = "imgProduct",
        widget = forms.FileInput(attrs={
            "class" : "form-control",
            "type" : "file",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",            
        })
    )

    category = forms.ChoiceField(
        label = "category", 
        
        choices = [
            ("Pets", "Pets"),
            ("Toys", "Toys"),
            ("Foods", "Foods"),
            ("Others", "Others"),
            ],

        widget = forms.Select(attrs = {
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )

    price = forms.IntegerField(
        label = "price",
        widget = forms.NumberInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",

        })
    )

    description = forms.CharField(
        label = "description", widget = forms.Textarea(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )
   
    class Meta:
        model = Product
        fields = ["name", "price", "imgProduct" , "category", "description"]


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        widget = forms.TextInput(attrs={
            "placeholder" : "First Name",
            "id" : "django_form",

        }), 
        max_length=100)
    last_name = forms.CharField(
        widget = forms.TextInput(attrs={
            "placeholder" : "Last Name",
            "id" : "django_form",

        }),
        max_length=100)
    email = forms.EmailField(
        widget = forms.TextInput(attrs={
            "placeholder" : "Email",
            "id" : "django_form",

        }),
        max_length=150)
    
    username = forms.CharField(
        widget = forms.TextInput(attrs={
            "placeholder" : "Username",
            "id" : "django_form",

        }), 
        max_length=20)

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "placeholder" : "Password",
            "id" : "django_form",
        }),
        max_length=20,
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "placeholder" : "Confirmation Password",
            "id" : "django_form",
        }),
        max_length=20,
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

landing/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import MakeProduct
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm
from django.http import JsonResponse, HttpResponse
from django.core import serializers


def see_desc(request, id):
    arg = Product.objects.get(pk=id)
    if request.method == 'POST':
        return redirect('/pembayaran/?id=' + str(id))
    context = {
        "barang" : arg,
        "page_title" : arg.name
    }
    return render(request, "landing/desc.html", context)

def index(request):


    all_product = Product.objects.all()

    arguments = {
        "page_title" : "Welcome to Your Pets",
        "products" : all_product,
    }
    return render(request, "landing/landing_page.html", arguments)

def newest_product(request):
    products = Product.objects.all().order_by("-id")[:3:]
    post_products = serializers.serialize('json', products)
    return HttpResponse(post_products, content_type="text/json-comment-filtered")

def add_product(request):
    if not request.user.is_authenticated:
        return redirect("landing:index")

    a_form = MakeProduct(request.POST or None, request.FILES or None)
    
    arguments = {
        "page_title" : "Add a Product",
        "form" : a_form,
    }

    if request.method == "POST" :
        if a_form.is_valid():
            a_form.save()
            return redirect("landing:add_my_product")
        else:
            a_form = MakeProduct()

    return render(request,"landing/addproduct.html", arguments)


def login_page(request):
    if request.user.is_authenticated:
        return redirect("landing:index")
    
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            request.session["user"] = request.POST["username"]
            return redirect("landing:index")
    
    form = AuthenticationForm()
    return render(request, "landing/login.html", {"form": form, "page_title" : "Login to Your Account"})

def signup_page(request):
    if request.user.is_authenticated:
        return redirect("landing:index")
    
    if request.method == "POST":
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()

            user.profile.first_name = form.cleaned_data.get('first_name')
            user.profile.last_name = form.cleaned_data.get('last_name')
            user.profile.email = form.cleaned_data.get('email')
            user.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            request.session["user"] = request.POST["username"]
            return redirect("landing:index")
        else:

            form = SignUpForm()
    form = SignUpForm()
    return render(request, "landing/signup.html", {"form" : form, "page_title" : "Sign Up to Your Pets"})


def logout_account(request):
    logout(request)
    return redirect("landing:index")

landing/templates/landing/snippets/bootstrap.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Dosis&display=swap" rel="stylesheet">

landing/templates/landing/snippets/bootstrapjquerypopper.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

landing/templates/landing/snippets/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f2d7ee;">
  <a class="navbar-brand" style="padding-top:0; padding-bottom:.65rem;" href="{% url 'landing:index' %}">
  	<img src="{% static 'LogoYourPets.png'%}" alt="" style="max-width:8rem">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'landing:index' %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'list_testimoni' %}">Testimoni</a>
          <a class="dropdown-item" href="{% url 'faq:faq_list' %}">FAQs</a>

          {% if user.is_authenticated %}
          <a class="dropdown-item" href="{% url 'landing:add_my_product' %}">Add Product</a>   
          {% endif %}      
        </div>
      </li>
    </ul>
    {% if user.is_authenticated %}
    <a href="{% url 'landing:logout_account' %}" class="btn btn-outline-danger my-2 my-sm-0" style="margin-right: 10px;">Logout</a>
  
    {% else %}

    <a href="{% url 'landing:login_page' %}" class="btn btn-outline-info my-2 my-sm-0" style="margin-right: 10px;">Login</a>
    <a href="{% url 'landing:signup_page' %}" class="btn btn-outline-info my-2 my-sm-0">Sign Up</a>
           
    {% endif %}
 
  </div>

</nav>