faq/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq_list, name='faq_list'),
    path('new/', views.new_faq, name='new_faq'),
    path('json/', views.faq_json, name='json'),
]

yourpets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("landing.urls")),
    path("", include("barang.urls")),
    path("", include("pembayaran.urls")),
    path("", include("testimoni.urls")),
    path("faqs/", include("faq.urls"))
]

faq/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Faq(models.Model):
    pertanyaan = models.CharField(max_length=100)
    jawaban = models.TextField(max_length=250)
    
    def __str__(self):
        return self.pertanyaan
    
    def getJawaban(self):
        return self.jawaban

faq/forms.py
from django import forms
from .models import Faq

class FaqForms(forms.ModelForm):
    class Meta:
        model = Faq
        fields = ['pertanyaan', 'jawaban']

        label = {
            'pertanyaan':'Pertanyaan ',
            'jawaban':'Jawaban ',
        }   

        widgets = {
            'pertanyaan':forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan pertanyaan Anda',
                }
            ),
            'jawaban':forms.Textarea(
                attrs = {
                    'class' : 'form-control',
                    'placeholder':'Masukkan jawaban Anda',
                }
            )
        }
    

faq/views.py
from django.shortcuts import render
from django.views import generic
from .models import Faq
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from .forms import FaqForms
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView

def faq_list(request):
    if request.method == 'GET':
        faqs = Faq.objects.order_by('pertanyaan')
        return render(request, 'faq_list.html', {'faqs':faqs})
    

def new_faq(request):
    if request.method == "POST":
        form = FaqForms(request.POST or None)
        if form.is_valid():
            faq = form.save()
            faq.save()
            return redirect('/faqs/')
    else:
        form = FaqForms()

    context = {
        'page_title':'Form FAQs',
        'form':form,
    }

    return render(request, 'new_faq.html', context)

def faq_json(request):
    data = list(Faq.objects.values('pertanyaan', 'jawaban'))
    return JsonResponse({'semuaFaq':len(data), 'faqs': data})

faq/templates/faq_list.html
{% extends 'landing/base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
{% endblock style %}

{% block content %}
    <title>Faq</title>
    <h1 class='faqsTitle'>FAQs</h1>
    <p class ='faqs'> Frequently Asked Questions</p>
    <div class="container-fluid" id="main-content">
        <ul class="list-unstyled" id="listOfFaqs">
            <!-- This is where testimonies go after fetching with ajax -->
            
        </ul>
        <div class="line" style= "margin-bottom:10px;" id="lineBawah" style="width:97.5%;"></div>
        <a href="{% url 'faq:new_faq' %}" class="btn" id="buttonSave" style="margin-top:50px; margin-bottom:25px;">Tambah FAQs</a>        
    </div>
{% endblock content %}


{% block script %}
    <script type="text/javascript" src="{% static 'js/faq.js' %}"></script>
{% endblock script %}

faq/templates/new_faq.html
{% extends 'landing/base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock style %}

{% block content %}
    <h1 class='addFaqs'>Tambah FAQs</h1>
    <div class="containerAdd">
        <form method="POST" class="post-form form-group">
        {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <h3 class="titlePertanyaan2"> {{ field.label }}</h3>
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="save btn btn-default" id="buttonSave" style="margin-top:50px; margin-bottom:25px;">Tambah</button>  
        </form>
    </div>
{% endblock content %}

{% block script %}
    <script type="text/javascript" src="{% static 'js/new.js' %}"></script>
{% endblock script %}