faq/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq_list, name='faq_list'),
    path('new/', views.new_faq, name='new_faq'),
    path('json/', views.faq_json, name='json'),
]

landing/urls.py
from django.urls import path, include
from landing.views import index
from landing.views import add_product
from landing.views import see_desc
from django.conf import settings
from django.conf.urls.static import static
from landing.views import logout_account
from landing.views import login_page
from landing.views import signup_page
from landing.views import newest_product

app_name = "landing"

urlpatterns = [
    path("", index, name='index'),
    path("addproduct/", add_product, name='add_my_product'),
    path("desc", index, name="description2"),
    path("desc/<int:id>/", see_desc, name="description"),
    path("login/", login_page, name="login_page"),
    path("signup/", signup_page, name="signup_page"),
    path("logout/", logout_account, name="logout_account"),
    path("ajax_call_products", newest_product, name="ajax_call"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yourpets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("landing.urls")),
    path("", include("barang.urls")),
    path("", include("pembayaran.urls")),
    path("", include("testimoni.urls")),
    path("faqs/", include("faq.urls"))
]

landing/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Product(models.Model):
    name = models.TextField()
    imgProduct = models.ImageField(upload_to = "images/", default="static/default/default.jpg")
    price = models.IntegerField()
    category = models.TextField()
    description = models.TextField()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=150)

    def __str__(self):
        return self.user.username
        
@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

landing/forms.py
from django import forms
from .models import Product
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class MakeProduct(forms.ModelForm):
    
    name = forms.CharField(
        label = "name", widget = forms.TextInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default"
        }),

    )

    imgProduct = forms.ImageField(
        label = "imgProduct",
        widget = forms.FileInput(attrs={
            "class" : "form-control",
            "type" : "file",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",            
        })
    )

    category = forms.ChoiceField(
        label = "category", 
        
        choices = [
            ("Pets", "Pets"),
            ("Toys", "Toys"),
            ("Foods", "Foods"),
            ("Others", "Others"),
            ],

        widget = forms.Select(attrs = {
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )

    price = forms.IntegerField(
        label = "price",
        widget = forms.NumberInput(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",

        })
    )

    description = forms.CharField(
        label = "description", widget = forms.Textarea(attrs={
            "class" : "form-control",
            "type" : "text",
            "aria-label" : "Default",
            "aria-describedby" : "inputGroup-sizing-default",
        })
    )
   
    class Meta:
        model = Product
        fields = ["name", "price", "imgProduct" , "category", "description"]


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        widget = forms.TextInput(attrs={
            "placeholder" : "First Name",
            "id" : "django_form",

        }), 
        max_length=100)
    last_name = forms.CharField(
        widget = forms.TextInput(attrs={
            "placeholder" : "Last Name",
            "id" : "django_form",

        }),
        max_length=100)
    email = forms.EmailField(
        widget = forms.TextInput(attrs={
            "placeholder" : "Email",
            "id" : "django_form",

        }),
        max_length=150)
    
    username = forms.CharField(
        widget = forms.TextInput(attrs={
            "placeholder" : "Username",
            "id" : "django_form",

        }), 
        max_length=20)

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "placeholder" : "Password",
            "id" : "django_form",
        }),
        max_length=20,
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "placeholder" : "Confirmation Password",
            "id" : "django_form",
        }),
        max_length=20,
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

landing/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import MakeProduct
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm
from django.http import JsonResponse, HttpResponse
from django.core import serializers


def see_desc(request, id):
    arg = Product.objects.get(pk=id)
    if request.method == 'POST':
        return redirect('/pembayaran/?id=' + str(id))
    context = {
        "barang" : arg,
        "page_title" : arg.name
    }
    return render(request, "landing/desc.html", context)

def index(request):


    all_product = Product.objects.all()

    arguments = {
        "page_title" : "Welcome to Your Pets",
        "products" : all_product,
    }
    return render(request, "landing/landing_page.html", arguments)

def newest_product(request):
    products = Product.objects.all().order_by("-id")[:3:]
    post_products = serializers.serialize('json', products)
    return HttpResponse(post_products, content_type="text/json-comment-filtered")

def add_product(request):
    if not request.user.is_authenticated:
        return redirect("landing:index")

    a_form = MakeProduct(request.POST or None, request.FILES or None)
    
    arguments = {
        "page_title" : "Add a Product",
        "form" : a_form,
    }

    if request.method == "POST" :
        if a_form.is_valid():
            a_form.save()
            return redirect("landing:add_my_product")
        else:
            a_form = MakeProduct()

    return render(request,"landing/addproduct.html", arguments)


def login_page(request):
    if request.user.is_authenticated:
        return redirect("landing:index")
    
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            request.session["user"] = request.POST["username"]
            return redirect("landing:index")
    
    form = AuthenticationForm()
    return render(request, "landing/login.html", {"form": form, "page_title" : "Login to Your Account"})

def signup_page(request):
    if request.user.is_authenticated:
        return redirect("landing:index")
    
    if request.method == "POST":
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()

            user.profile.first_name = form.cleaned_data.get('first_name')
            user.profile.last_name = form.cleaned_data.get('last_name')
            user.profile.email = form.cleaned_data.get('email')
            user.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            request.session["user"] = request.POST["username"]
            return redirect("landing:index")
        else:

            form = SignUpForm()
    form = SignUpForm()
    return render(request, "landing/signup.html", {"form" : form, "page_title" : "Sign Up to Your Pets"})


def logout_account(request):
    logout(request)
    return redirect("landing:index")

landing/templates/landing/addproduct.html
{% extends 'landing/base.html' %}

{% load static %}


{% block style %}

{% endblock style %}



{% block content %}

<div class="container-fluid" style="margin-bottom: 5%;">
    <p class="text-center" style="font-size:200%;">Add Product</p>
</div>

<div class="container">
    <form action="{% url 'landing:add_my_product' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Name </span>
                    </div>
                    {{ form.name }}
                </div>
            </div>

            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Image </span>
                    </div>
                    {{ form.imgProduct }}
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Price</span>
                    </div>
                    {{ form.price }}
                </div>
            </div>

            <div class="col">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-default">Category</span>
                    </div>
                    {{ form.category }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <p class="input-group-text" id="inputGroup-sizing-default">Description</p>
                {{ form.description }}
            </div>
        </div>

        <div class="row">
            <div class="col">
                <button type="submit" style="margin-top: 2%;">Add This Product</button>
            </div>
        </div>
                        
    </form>

</div>




{% endblock content %}

landing/templates/landing/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        {% include 'landing/snippets/bootstrap.html' %}

        {% block style %}

        {% endblock style %}
        
        <title>{{ page_title }}</title>
    </head>
    <body style="font-family:Dosis;">
        <div id="navbar">
            {% include 'landing/snippets/navbar.html' %}
        </div>
        {% block content %}

        {% endblock content %}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        {% include 'landing/snippets/bootstrapjquerypopper.html' %}
        {% block script %}
        
        {% endblock script %}
    </body>
</html>

landing/templates/landing/desc.html
{% extends 'landing/base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/landing.css' %}">

<style>
.img {
    position: relative;
    float: left;
    width:  50vh;
    height: 42vh;
    background-position: 50% 50%;
    background-repeat:   no-repeat;
    background-size:     cover;
    border-radius: 5%;
}
</style>
{% endblock style %}


{% block content %}

<div class="container" style="margin-bottom: 20px; margin-top: 10px;">
    <div class="page-header">
        <h1>{{ barang.name }}</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <img src="{{ barang.imgProduct.url }}" style="border-radius: 10%;" class="img" alt="Gambar Produk">
        </div>
        <div class="col">
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary">Beli Produk Ini</button>
            </form>
            <p style="font-size: 3rem;">IDR {{ barang.price }}</p>
        </div>
    </div>        
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <p class="text-center"><br>{{ barang.description }}</p>
        </div>
        <div class="col">
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}


{% endblock script %}

landing/templates/landing/landing_page.html
{% extends 'landing/base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/landing.css' %}">
<link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

<style>
html{
    font-family: Quicksand, sans-serif;
}

.img {
    position: relative;
    float: left;
    width:  50vh;
    height: 42vh;
    background-position: 50% 50%;
    background-repeat:   no-repeat;
    background-size:     cover;
    border-radius: 5%;
}

.img_product{
    position: relative;
    float: left;
    width:  255px;
    height: 230px;
    background-position: 50% 50%;
    background-repeat:   no-repeat;
    background-size:     cover;

}
</style>
{% endblock style %}


{% block content %}

<div class="container-fluid">
    <p class="text-center" style="font-family:'Quicksand',sans-serif; font-size: 40px; margin:9vh;">Hey there,
        <br>Let's find your pets and their needs here...!!</p>
</div>

<div class="container-fluid" id="newest_product" style="background-color: #F7F4F3;">
    <div>
        <br>
        <h1 style="font-family:'Quicksand Bold', sans-serif; font-size: 30px;">Our Newest Products</h1>
        <br>
    </div>
    
    <div class="row" id="to_be_filled">

    </div>
    <br>

</div>


<div class="container-fluid"  id="for_all_product" style="margin-bottom:5rem;">
    <div>
        <br><br><h1 style="font-family:'Quicksand Bold',sans-serif; font-size: 30px;">All Products</h1><br>
    </div>

    <div class="row">
    {% for product in products %}
        <div class="card mx-3 my-2" style="width: 16rem;">
            <img src="{{ product.imgProduct.url }}" class="img_product card-img-top" alt="Gambar Produk">
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}<br>IDR {{ product.price }}</h5>
                <a href="{% url 'landing:description' product.id %}" class="btn btn-primary pull-right" style="float: left;">Lihat</a>
                <p> </p>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

<img src="" alt="">
{% endblock content %}

{% block script %}


<script>
    jQuery(document).ready(function($){
        $('.img_product').hover(function() {
            $(this).css("cursor", "pointer");
            $(this).toggle({
            effect: "scale",
            percent: "90%"
            },200);
        }, function() {
            $(this).toggle({
            effect: "scale",
            percent: "80%"
            },200);

        });
    
        $.ajax({
            url: "{% url 'landing:ajax_call' %}",
            success : function(result){



                for (i = 0; i < result.length; i++){

                    let this_id = parseInt(result[i].pk);

                    var temp = `<a href="/desc/${this_id}">`;
                    
                    data = 
                        "<div class='col'>" +
                            temp +
                                "<img src=\"media/" + result[i].fields.imgProduct + "\" class=\"img img-thumbnai;\" alt=\"image newest\"/>" +
                            "</a>" + 
                        "</div>";

                    $("#to_be_filled").append(data);


    
    
                }
            }
        })
    })
</script>


{% endblock script %}

landing/templates/landing/login.html
{% extends 'landing/base.html' %}

{% load static %}



{% block style %}
<style>
#id_username{
    width: 200px;
    margin-bottom: 15px;
}
#id_password{
    width: 200px;

}
</style>

{% endblock style %}


{% block content %}
<div class="container text-center">
    <h2 style="margin: 20px;">Please Login to Your Account</h2>
    <form action="{% url 'landing:login_page' %}" method="POST">
        {% csrf_token %}
        <div>
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div>
            {{ form.password.label_tag }}
            {{ form.password }}
        </div>
        
        <button type="submit" class="btn btn-outline-primary btn-sm">Login</button>
    </form>
</div>
{% endblock content %}
{% block script %}

        
{% endblock script %}

landing/templates/landing/signup.html
{% extends 'landing/base.html' %}

{% load static %}



{% block style %}
<link href="{% static 'css/signup.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">

<style>
#django_form{
    margin: 10px;
    margin-top: 10px;

}
</style>
{% endblock style %}


{% block content %}
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->


<div class="main-w3layouts wrapper">
    <h1 id="title_signup">Sign Up a YourPets Account</h1>
    <div class="main-agileinfo">
        <div class="agileits-top">
            <form action="{% url 'landing:signup_page' %}" method="POST">

                {% csrf_token %}
                <div>
                    {{ form.first_name }}

                </div>
                <div>
                    {{ form.last_name }}
                </div>
                <div>
                    {{ form.email }}
                </div>
                <div>
                    {{ form.username }}
                </div>
                <div>
                    {{ form.password1 }}
                </div>
                <div>
                    {{ form.password2 }}
                </div>
                
                <input type="submit" value="SIGNUP">
            </form>
            <p>Already have an Account? <a href="{% url 'landing:login_page' %}"> Login Now!</a></p>
        </div>
    </div>
    <!-- copyright -->
    <div class="colorlibcopy-agile">
        <p>© 2019 YourPets. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
    </div>
    <!-- //copyright -->
    <br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br>
    <br><br><br>
                
    <ul class="colorlib-bubbles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>

{% endblock content %}

{% block script %}
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
{% endblock script %}